apiVersion: v1
kind: Service
metadata:
  labels:
    app: mapl-adapter-dep
  name: mapl-adapter-dep
  namespace: istio-system
spec:
  ports:
  - name: port7782
    port: 7782
    protocol: TCP
    targetPort: 7782
  selector:
    app: mapl-adapter-dep
  type: ClusterIP
---