apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mapl-adapter-dep
  namespace: istio-system
  labels:
    app: mapl-adapter-dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: mapl-adapter-dep
    spec:
      imagePullSecrets: # needs to be under istio-system namespace
       - name: docker-secret
      containers:
      - image: octarinesec/mapl_adapter:latest
        imagePullPolicy: Always
        name: mapl-adapter-dep
        volumeMounts:
          - name: config-volume
            mountPath: /etc/rules
        ports:
        - containerPort: 7782
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

        env:
        - name: ADAPTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOGGING
          value: "true"
        - name: CACHE_TIMEOUT_SECS
          value: "3"
        - name: ISTIO_TO_SERVICE_NAME_CONVENTION
          value: "IstioUid"  # other options: "IstioWorkloadAndNamespace"

      volumes:
        - name: config-volume
          configMap:
            name: mapl-adapter-rules-config-map
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
